# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - third_party/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # 强制要求良好的类型安全
    always_declare_return_types: true
    avoid_print: true
    # 安全性与空安全
    cancel_subscriptions: true
    close_sinks: true
    avoid_empty_else: true
    # 强制组件不可变性与最佳实践
    prefer_const_constructors: true
    prefer_const_declarations: true
    use_key_in_widget_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true


# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
